import { FileText, X } from 'lucide-react';
import { cn, formatDocumentDate } from '@/utils';

export const ChatInfoPanel = ({ conversation, documents = [], isOpen, onClose, messageCount }) => (
  <aside aria-label="Conversation details" className={cn('fixed inset-y-0 right-0 z-modal flex w-[min(20rem,calc(100vw-1rem))] translate-x-full flex-col border-l border-border bg-card transition-transform duration-theme xl:static xl:z-base xl:w-auto xl:translate-x-0', isOpen && 'translate-x-0')}>
    <header className="flex shrink-0 items-center justify-between border-b border-border px-gutter py-4"><h2 className="font-display text-sm font-semibold text-content-primary">Conversation details</h2><button aria-label="Close conversation details" className="inline-flex size-9 items-center justify-center rounded-control text-content-secondary hover:bg-canvas xl:hidden" onClick={onClose} type="button"><X aria-hidden="true" size={18} /></button></header>
    <div className="min-h-0 space-y-layout overflow-y-auto p-gutter"><section><p className="text-xs font-medium uppercase tracking-wide text-content-muted">Overview</p><dl className="mt-3 space-y-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-content-secondary">Created</dt><dd className="text-right font-medium text-content-primary">{conversation?.createdAt ? formatDocumentDate(conversation.createdAt) : '—'}</dd></div><div className="flex justify-between gap-3"><dt className="text-content-secondary">Provider</dt><dd className="text-right font-medium text-content-primary">{conversation?.provider || '—'}</dd></div><div className="flex justify-between gap-3"><dt className="text-content-secondary">Messages</dt><dd className="text-right font-medium text-content-primary">{messageCount}</dd></div></dl></section><section><p className="text-xs font-medium uppercase tracking-wide text-content-muted">Your documents</p>{documents.length ? <ul className="mt-3 space-y-2">{documents.map((document) => <li className="flex items-center gap-2 rounded-control bg-canvas px-3 py-2 text-sm text-content-secondary" key={document.id}><FileText aria-hidden="true" className="shrink-0 text-accent" size={16} /><span className="min-w-0 flex-1 truncate">{document.title || document.originalFileName}</span></li>)}</ul> : <p className="mt-3 text-sm leading-6 text-content-secondary">No uploaded documents yet.</p>}</section></div>
  </aside>
);
