import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { X } from 'lucide-react';
import { DOCUMENT_CATEGORIES } from '@/constants';
import { UploadDropzone } from './UploadDropzone';
import { UploadQueue } from './UploadQueue';

export const UploadDialog = ({ isOpen, onCancelUpload, onClose, onRemoveQueueItem, onRetryUpload, onUpload, queue }) => {
  const { handleSubmit, register } = useForm({ defaultValues: { category: 'others', description: '', tags: '', title: '' } });
  const [files, setFiles] = useState([]);
  const submit = (values) => { if (files.length) onUpload(files, values); };
  if (!isOpen) return null;
  return <div aria-modal="true" className="fixed inset-0 z-modal flex items-center justify-center bg-secondary/40 p-gutter" role="dialog" aria-label="Upload documents"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-panel border border-border bg-card p-gutter shadow-floating"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold text-content-primary">Upload documents</h2><button aria-label="Close upload dialog" className="inline-flex size-9 items-center justify-center rounded-control text-content-secondary hover:bg-canvas" onClick={onClose} type="button"><X aria-hidden="true" size={18} /></button></div><form className="mt-gutter space-y-gutter" onSubmit={handleSubmit(submit)}><UploadDropzone onFiles={setFiles} />{files.length > 0 && <p className="text-sm text-content-secondary">{files.length} file{files.length === 1 ? '' : 's'} ready to upload.</p>}<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium text-content-primary">Category<select className="mt-1.5 w-full rounded-control border border-border bg-surface px-3 py-2 text-sm" {...register('category')}>{DOCUMENT_CATEGORIES.map((category) => <option key={category} value={category}>{category}</option>)}</select></label><label className="text-sm font-medium text-content-primary">Title <span className="text-content-muted">(single upload)</span><input className="mt-1.5 w-full rounded-control border border-border bg-surface px-3 py-2 text-sm" {...register('title')} /></label></div><label className="block text-sm font-medium text-content-primary">Description<textarea className="mt-1.5 min-h-20 w-full rounded-control border border-border bg-surface px-3 py-2 text-sm" {...register('description')} /></label><label className="block text-sm font-medium text-content-primary">Tags <span className="text-content-muted">(comma separated)</span><input className="mt-1.5 w-full rounded-control border border-border bg-surface px-3 py-2 text-sm" {...register('tags')} /></label><button className="w-full rounded-control bg-primary px-4 py-2.5 text-sm font-semibold text-content-inverse disabled:opacity-50" disabled={!files.length} type="submit">Upload {files.length || ''} file{files.length === 1 ? '' : 's'}</button><UploadQueue items={queue} onCancel={onCancelUpload} onRemove={onRemoveQueueItem} onRetry={onRetryUpload} /></form></div></div>;
};
