import { Bot, FileText, Search, Settings, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

const icons = { action: Sparkles, chat: Bot, document: FileText, settings: Settings };
export const SearchInput = ({ autoFocus = false, onChange, value }) => <label className="relative block"><span className="sr-only">Search LifeOS</span><Search aria-hidden="true" className="absolute left-4 top-1/2 -translate-y-1/2 text-content-muted" size={21} /><input autoFocus={autoFocus} className="w-full rounded-panel border border-border bg-card py-4 pl-12 pr-4 text-base text-content-primary outline-none placeholder:text-content-muted focus:border-primary" onChange={(event) => onChange(event.target.value)} placeholder="Search chats, documents, settings…" value={value} /></label>;
export const SearchFilterBar = ({ active, onChange }) => <div className="flex gap-2 overflow-x-auto">{['all', 'chats', 'documents', 'settings'].map((filter) => <button className={`rounded-pill px-3 py-1.5 text-sm capitalize ${active === filter ? 'bg-primary text-content-inverse' : 'border border-border bg-card text-content-secondary'}`} key={filter} onClick={() => onChange(filter)} type="button">{filter}</button>)}</div>;
export const SearchResultCard = ({ result, onOpen }) => { const Icon = icons[result.type] || Search; return <Link className="flex items-center gap-3 rounded-card border border-border bg-card p-3 transition-[transform,box-shadow] duration-theme hover:-translate-y-0.5 hover:shadow-card" onClick={onOpen} to={result.to}><span className="flex size-9 items-center justify-center rounded-control bg-canvas text-primary"><Icon aria-hidden="true" size={18} /></span><span className="min-w-0"><span className="block text-sm font-medium text-content-primary">{result.title}</span><span className="mt-1 block truncate text-xs text-content-secondary">{result.description}</span></span></Link>; };
export const RecentSearchList = ({ history, onClear, onSelect }) => <section><div className="flex justify-between"><h2 className="font-display text-sm font-semibold text-content-primary">Recent searches</h2>{history.length > 0 && <button className="text-xs text-primary" onClick={onClear} type="button">Clear</button>}</div><div className="mt-3 flex flex-wrap gap-2">{history.map((item) => <button className="rounded-pill border border-border bg-card px-3 py-1.5 text-sm text-content-secondary" key={item} onClick={() => onSelect(item)} type="button">{item}</button>)}</div></section>;
export const EmptySearchState = () => <div className="py-layout text-center"><Search aria-hidden="true" className="mx-auto text-content-muted" size={30} /><h2 className="mt-3 font-display text-lg font-semibold text-content-primary">Search across LifeOS</h2><p className="mt-1 text-sm text-content-secondary">Find conversations, documents, settings, and quick actions.</p></div>;
